### ISSUE TITLE
NX4832K035_Model 10-3.5inch_SMPLX_Enhanced_v1.05.HMI P25 TG limited to 4 characters.

### ISSUE THREAD

**Issue by vk7hse** [PD0DIB/Nextion_HAM-radio-screens#13]
NX4832K035_Model 10-3.5inch_SMPLX_Enhanced_v1.05.HMI on the P25 page  is currently limiting the TalkGroup to 4 characters. So for example when using the 10xxx TalkGroups the have the last digit cut off so TG10400 only displays as TG1040.

**Comment by vk7hse** [comment]
This also applies to the Duplex Model 10 3.5" screen as well on P25.

**Comment by PD0DIB** [comment]
Thanks for notice that!
Solved: changed fontsize to make fit the content.

**Comment by PD0DIB** [comment]
Solved by changing fontsize to make fit the content in this field
