### ISSUE TITLE
NX3224K024_Model 10-2.4inch_DPLX_Enhanced has 2 TX labels on ID:0 image, one should be TX and the other RX

### ISSUE THREAD

**Issue by rfanfant** [PD0DIB/Nextion_HAM-radio-screens#14]
The lower TX label needs to be modified to be RX in DPLX mode.

**Comment by PD0DIB** [comment]
Will be changed in next build which is planned between 08-12 SEP 2020

**Comment by PD0DIB** [comment]
Redesigned all Duplex 2.4 & 2.8 screens, includin labels correct and PowerOff/Boot buttons bigger and correct working
