### ISSUE TITLE
3.2 M10 Screen Temperature block

### ISSUE THREAD

**Issue by Bill-Paulus** [PD0DIB/Nextion_HAM-radio-screens#15]
NX4024K032_Model 10-3.2inch_SMPLX_Enhanced_v1.05.HMI
The temperature block is not reporting anything on the MMDVM page.
None of the blocks are reparting in the C4FM page.
As you told me not to edit the fields for tx and rx frequency and nothing is populated in those fields.
![image0](https://user-images.githubusercontent.com/44480551/92418071-a7db1380-f133-11ea-9a79-a3d8d1178431.jpeg)

![image2](https://user-images.githubusercontent.com/44480551/92418076-ab6e9a80-f133-11ea-890b-7975d388f6b6.jpeg)
![image3](https://user-images.githubusercontent.com/44480551/92418078-ad385e00-f133-11ea-91d7-9cef8213696b.jpeg)

**Comment by PD0DIB** [comment]
On test system no major problems; did some code debugging (found 1 bug, resolved) and changed some fonts and color-scheme for better readability.
Tested extensively on a Jumbo (Simplex)
