### ISSUE TITLE
2.4 M10 Enhanced buttons backwards

### ISSUE THREAD

**Issue by Bill-Paulus** [PD0DIB/Nextion_HAM-radio-screens#16]
NX3224K024_Model 10_2.4inch_SMPLX_Enhanced_v1.05.HMI Power Off reboots the pi and Reboot powers down the pi.

**Comment by PD0DIB** [comment]
2.4, 2.8 inch, both Basic & Enhanced for Simplex and Duplex are undergoing redesign.
Will dubble-check those buttons.

**Comment by PD0DIB** [comment]
Simplex: New build: corrected Boot & PowerrOff buttons; some color-scheme changes
