### ISSUE TITLE
NX3224K028_Model 10-2.4inch_DPLX_Enhanced_v1.05.HMI no longer exists?

### ISSUE THREAD

**Issue by rfanfant** [PD0DIB/Nextion_HAM-radio-screens#19]
The Duplex Enhanced version of the Nextion NX3224K028 no longer exists. I have several duplex hotspots which now appear as Simplex HS.

-rob N7QT

**Comment by PD0DIB** [comment]
My mistake.. mixed-up someting with uploading modified files; corrected, avaialble again...
