### ISSUE TITLE
Touch Screen Power and Reboot buttons on MMDVMI Screen not working on Model 10

### ISSUE THREAD

**Issue by jphsv1** [PD0DIB/Nextion_HAM-radio-screens#24]
I recently purchased a ZumSpot Nextion 3.5 Rpi and I updated the Nextion Driver succesfully and uploaded an edited version of the Model 10 TFT file (NX4832K035_Model 10-3.5inch_SMPLX_Enhanced_v1.05.HMI). Things are working well but the power and reboot buttons do not function on the MMDVMl main screen. I did not change any details in the Editor for those two buttons.  

Note: It is nice that the screen is now flipped so my power cord is attached at the top. I was able to change the date and time format for US UTF-8, and changed the timezone but then date/time string did not fit on the screen - was truncated. Fortunately, I just moved it to a different location so it could be seen with the same size font.

I just closed this because I didn't realize that the buttons actually work, they don't provide feedback. I'll have to figure out how to display a short duration "Shutting Down" or "Rebooting" message after pressing the buttons.

**Comment by w9ndu** [comment]
TGIF ASK ROBERT K4WZV FOR HELP
BARRY W9NDU 73
ONE ? HOW DID YOU FLIP THE SCREEN SORRY MY CAP LOCK WAS ON

**Comment by jphsv1** [comment]
Robert,

You have to use the Nextion Editor, load your screen version, then select the device icon, then you will be given rotation options. I used the Model 10 release, made the rotation change, then wrote it to a microSD card and inserted it into the Nextion Screen and powered it on for it to load. Once loaded, I removed the MicroSD card after successful upload and rebooted.

73,
K2LAT

**Comment by w9ndu** [comment]
Ty but my name is Barry w9ndu
But that's OK
