### ISSUE TITLE
IP address

### ISSUE THREAD

**Issue by VK5MW** [PD0DIB/Nextion_HAM-radio-screens#3]
Going to settings page to change the screen brightness. On return to the home screen there is no IP address for some time

**Comment by PD0DIB** [comment]
Yep, it is in a 'life-refresh' mode, so on the next cycle it is there.
I will change it in a later update to store the address in a variable field
which is updated in the background and displayed instantly
Tnx for input
73

====================
met vriendelijke groet | Kind Regards,
Rob van Rheenen

Op do 26 jul. 2018 06:22 schreef VK5MW <notifications@github.com>:
