### ISSUE TITLE
Simplex Version 7"

### ISSUE THREAD

**Issue by VK5MW** [PD0DIB/Nextion_HAM-radio-screens#4]
Simplex version shows duplex frequencies.

**Comment by PD0DIB** [comment]
You have to add/correct those into your own frequencies 'by hand' with the
Nextion Editor
73

====================
met vriendelijke groet | Kind Regards,
Rob van Rheenen

Op do 26 jul. 2018 06:24 schreef VK5MW <notifications@github.com>:

**Comment by VK5MW** [comment]
Could it be a feature on the settings page. Set the variable to use on all pages. Just a thought
    	
    	

    	Michael Wright4 Formosa RoadRoxby DownsSA 5725041789636408 86710941
    
  




On Fri, Jul 27, 2018 at 12:24 AM +0930, "Rob van Rheenen" <notifications@github.com> wrote:










You have to add/correct those into your own frequencies 'by hand' with the

Nextion Editor

73



====================

met vriendelijke groet | Kind Regards,

Rob van Rheenen



Op do 26 jul. 2018 06:24 schreef VK5MW <notifications@github.com>:
