### ISSUE TITLE
No info in modem mode

### ISSUE THREAD

**Issue by Tomxtal** [PD0DIB/Nextion_HAM-radio-screens#5]
I'm using BI7JTA duplex board V1.01 FW 1.4.7 I can not get the Pi-Star Modem setting to work as in I can only get basic information but when in in the /dev/tyyUSB0 USB to TTL convert it works just fine. I have the install the NextionDriver. Model 8.

**Comment by PD0DIB** [comment]
NextionDriver via modem connection isn't supported yet in Pi-Star.
Will be fixed soon
So USB connector is the only option for now.
73 de PD0DIB | Rob

====================
met vriendelijke groet | Kind Regards,
Rob van Rheenen

Op ma 10 sep. 2018 18:20 schreef Tom Crystal <notifications@github.com>:

**Comment by PD0DIB** [comment]
See wiki. From 12SEP2018 (new release of Pi-Star) it is possible to connect to the Nextion modem pinheader. See Wiki ==FAQ's for implementation notes
