### ISSUE TITLE
Nextion Screen display Model 7, V2.2

### ISSUE THREAD

**Issue by VE2SPY** [PD0DIB/Nextion_HAM-radio-screens#6]
I can't activate the Last Heard fields in DMR screen,

The RSSI and BER fields only works in TX Mode ?

I use a Duplex MMDVM board from BI7JTA on a Raspberry Pi 3 B+

Any solutions?

Thanks

Michel

**Comment by wh42933** [comment]
Michel 
 did you make sure rt->tx and tx->rx  lines are not swapped. ( I know sounds silly but...) BER work in both directions and I believe the RSSI is tx only.  Is the mmdvm receiving the signal from the radio ? 
just a few points to check.

**Comment by VE2SPY** [comment]
Hi,

Thanks for the help William,

I have installed the Nextion driver and now my display shows the last heard (LH) for both time slots but the BER is still blank.

To answer your questions, my TX and RX fields are correct and the MMDVM is not receiving the signal from the radio.

I am working on it.

Thanks again, if you have any other ideas you are more then welcome.

Please excuse my English

I’ll keep you posted on progress...

73’s from VE2SPY

Michel
PS : Please have a very nice New Year.

De : williamharding
Envoyé le :30 décembre 2018 16:29
À : PD0DIB/Nextion_HAM-radio-screens
Cc : VE2SPY; Author
Objet :Re: [PD0DIB/Nextion_HAM-radio-screens] Nextion Screen display Model7, V2.2 (#6)

Michel
did you make sure rt->tx and tx->rx lines are not swapped. ( I know sounds silly but...) BER work in both directions and I believe the RSSI is tx only. Is the mmdvm receiving the signal from the radio ?
just a few points to check.

**Comment by PD0DIB** [comment]
BER and RSSI are only visible in TX mode (your values), not in RX mode

====================
met vriendelijke groet | Kind Regards,
Rob van Rheenen

Op zo 30 dec. 2018 23:19 schreef VE2SPY <notifications@github.com:

**Comment by VE2SPY** [comment]
Hi Rob,

Thanks for the info.

That’s what I thought.

I have installed the Model 8, Globe Duplex display for 3.2 inches Nextion screen.

I am getting a lot more info but the Dashboard screen is not filling up; I figure there is still some work to do on this said display.

Thanks again.

73’s from VE2SPY


Michel
PS : Very happy to have joined Github Group.
Happy New Year to you and your familly !!!

De : Rob van Rheenen
Envoyé le :30 décembre 2018 17:41
À : PD0DIB/Nextion_HAM-radio-screens
Cc : VE2SPY; Author
Objet :Re: [PD0DIB/Nextion_HAM-radio-screens] Nextion Screen display Model7, V2.2 (#6)

BER and RSSI are only visible in TX mode (your values), not in RX mode

====================
met vriendelijke groet | Kind Regards,
Rob van Rheenen

Op zo 30 dec. 2018 23:19 schreef VE2SPY <notifications@github.com:

**Comment by wh42933** [comment]
Michel 
I f few ideas, under admin click on 'Live Logs' and see if it is hearing the radio. if it is it should show important info to further diagnose problems. 

here's an example from a quick test of a TYT md380 on one of my pi-star dmr set units : 
tested on  Parrot
Starting logging, please wait...
M: 2018-12-31 02:58:18.828 DMR Slot 2, received RF voice header from N3VMT to TG 9990
M: 2018-12-31 02:58:19.366 DMR Slot 2, received RF end of voice transmission, 0.4 seconds, BER: 0.1%, RSSI: -75/-63/-65 dBm
M: 2018-12-31 02:58:26.709 DMR Slot 2, received RF voice header from N3VMT to TG 9990
M: 2018-12-31 02:58:27.969 DMR Slot 2, received RF end of voice transmission, 1.1 seconds, BER: 1.3%, RSSI: -75/-63/-65 dBm

this shows BER % and RSSI . Hope this is a little more helpful.

**Comment by VE2SPY** [comment]
Hi again,

Very interesting info.

I was not familiar with this part of Pi-Star.

I have just tried it and yes it provides a lot of useful infos.

I still have a lot to learn and experiment.

That is what it is all about...

Sincerely greatfull for your time and infos.


73’s from VE2SPY

Michel 

De : williamharding
Envoyé le :30 décembre 2018 22:01
À : PD0DIB/Nextion_HAM-radio-screens
Cc : VE2SPY; Author
Objet :Re: [PD0DIB/Nextion_HAM-radio-screens] Nextion Screen display Model7, V2.2 (#6)

Michel
I f few ideas, under admin click on 'Live Logs' and see if it is hearing the radio. if it is it should show important info to further diagnose problems.
here's an example from a quick test of a TYT md380 on one of my pi-star dmr set units :
tested on Parrot
Starting logging, please wait...
M: 2018-12-31 02:58:18.828 DMR Slot 2, received RF voice header from N3VMT to TG 9990
M: 2018-12-31 02:58:19.366 DMR Slot 2, received RF end of voice transmission, 0.4 seconds, BER: 0.1%, RSSI: -75/-63/-65 dBm
M: 2018-12-31 02:58:26.709 DMR Slot 2, received RF voice header from N3VMT to TG 9990
M: 2018-12-31 02:58:27.969 DMR Slot 2, received RF end of voice transmission, 1.1 seconds, BER: 1.3%, RSSI: -75/-63/-65 dBm
this shows BER % and RSSI . Hope this is a little more helpful.

**Comment by VE2SPY** [comment]
Now, everything seems in good working order but waitting for Model 8 V2.2 updates to activate the touch screen buttons.

Also a Dashboard version for 3.2 inches screens would be appreciated.

Thank you all.

I really wish that I will be able to return the help for other friends.

Michel
VE2SPY

**Comment by PD0DIB** [comment]
Model 8 is supporting touch buttons, but only if it's connected via USBtoTTL adapter.
Unfortunately, the modem pinheader on all boards ee know of are communicating one way only, not receiving commands from the Nextion screen....

**Comment by VE2SPY** [comment]
Hi Rob,

Thanks for the info.

What puzzles me is that even If my screen is not connected throught a USB adaptor, the HOME and INFO press buttons works correctly as the OFF-ON and REBOOT buttons do not respond???

Thanks again for your prompt repply and time.

Have a good day!

73’s from VE2SPY

Michel

De : Rob van Rheenen
Envoyé le :14 janvier 2019 15:51
À : PD0DIB/Nextion_HAM-radio-screens
Cc : VE2SPY; State change
Objet :Re: [PD0DIB/Nextion_HAM-radio-screens] Nextion Screen display Model7, V2.2 (#6)

Model 8 is supporting touch buttons, but only if it's connected via USBtoTTL adapter.
Unfortunately, the modem pinheader on all boards

**Comment by JeffHochberg** [comment]
Rob,

There are some people that have been clever enough to figure out how to run their Nextion displays wirelessly via Bluetooth.

Do you happen to know if the touch buttons will work over the Bluetooth connection? I believe it’s just a serial connection over Bluetooth, so in theory it should effectively operate the same as the USB-TTL interface.

I haven’t tried to set mine up like this...yet. Just curious to know what the expected behavior is.

Thank you sir!

-JeffH

Jeff Hochberg
W4JEW

Sent from my iPhone

On Jan 14, 2019, at 4:34 PM, VE2SPY <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Rob,

Thanks for the info.

What puzzles me is that even If my screen is not connected throught a USB adaptor, the HOME and INFO press buttons works correctly as the OFF-ON and REBOOT buttons do not respond???

Thanks again for your prompt repply and time.

Have a good day!

73’s from VE2SPY

Michel

De : Rob van Rheenen
Envoyé le :14 janvier 2019 15:51
À : PD0DIB/Nextion_HAM-radio-screens
Cc : VE2SPY; State change
Objet :Re: [PD0DIB/Nextion_HAM-radio-screens] Nextion Screen display Model7, V2.2 (#6)

Model 8 is supporting touch buttons, but only if it's connected via USBtoTTL adapter.
Unfortunately, the modem pinheader on all boards

**Comment by PD0DIB** [comment]
Home and Unfi are handled within the Nextion itself, no need to communicate
with the hotspot.

====================
met vriendelijke groet | Kind Regards,
Rob van Rheenen

Op ma 14 jan. 2019 22:34 schreef VE2SPY <notifications@github.com:
