### ISSUE TITLE
Need to use LTS version of Nextion Editor

### ISSUE THREAD

**Issue by sgrimee** [PD0DIB/Nextion_HAM-radio-screens#9]
When importing these layouts in the current version of Nextion Editor, I got a notification that the project needs to be upgraded, which I attempted, but the process led to a few array out of bound errors.
The end result was that several fonts were garbled on the display (unreadable).
Installing the [LTS version](https://nextion.tech/nextion-editor/#_section2) (legacy) of the editor solved the problem for me.

**Comment by PD0DIB** [comment]
Yep, ... I'm in the process to convert fonts, but this is a slow process due to little time at the moment

**Comment by PD0DIB** [comment]
Closed - files are adpted to new editor fonts
